name: docker

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t aion-os:ci .
